### ISSUE TITLE
crash when getting focus

### ISSUE THREAD

**Issue by winxpqq955** [NathanW-05/OwlHook#2]
It looks like this

[https://streamable.com/s52y7o](https://streamable.com/s52y7o)

[hs_err_pid2880.log](https://pastebin.mozilla.org/j8QEZsxL)

maybe there is problem with wndproc hook, or somewhere else

**Comment by NathanW-05** [comment]
That's really weird, huh. Never came across that during any testing. I hate to say that I have no clue, but I seriously don't -- I would look into this... but I have long quit and don't even have coding programs: sorry man. Are you using my pre-compiled version, or did you build it yourself? It's likely I fucked something up when releasing this; I didn't even test it on my own PC -- much less another computer.

**Comment by winxpqq955** [comment]
> 

my own compiled version and the pre-compiled version both crashed, it's weird, what jdk are you using?

**Comment by NathanW-05** [comment]
Oracle JDK 8u311 iirc

**Comment by purpl3r0se** [comment]
working perfectly fine for me, only issue is when changing resolution aka going into full screen and out, can no longer open the menu.

**Comment by NathanW-05** [comment]
> working perfectly fine for me, only issue is when changing resolution aka going into full screen and out, can no longer open the menu.

That's actually a known issue that I fixed in a more advanced and finished unreleased version. I would patch it but no longer have the project nor code anymore. Sorry :(

**Comment by purpl3r0se** [comment]
I also tried using the set_health function whenever you get the local player, although it just crashed when i used it

**Comment by NathanW-05** [comment]
Mhm, that should work. Make a fork and add the code you changed ill take a look.

**Comment by purpl3r0se** [comment]
> Mhm, that should work. Make a fork and add the code you changed ill take a look.

I don't have alot of C++ experience + i already deleted the project since i was just testing, but all i did was use the mappings given, include them, use them to get the local player using the function and then with that i just did Player.set_health(x), x is replaced with a float from a slider in imgui (set_health takes float therefore a float slider)

**Comment by winxpqq955** [comment]
my bad, crash was caused by openjdk, everything works fine with oracle jdk
